### ISSUE TITLE
Create RecipeIngredients component

### ISSUE THREAD

**Issue by AndriyBabiy** [asaulyak/foodies-fe#18]
"Компонент отримує в пропсах дані та відмальовує список елементів, кожен з яких містить в собі:
- зображення інгредієнта або відповідний плейсхолдер
- назву інгредієнта
- його кількість"

**Comment by didukhroma** [comment]
DB doesn't have property quantity.
For now I added placeholder
DB

![Image](https://github.com/user-attachments/assets/5b85ef04-196e-43f9-bfc0-1637c0a6c05a)

Answer
![Image](https://github.com/user-attachments/assets/5d06d89d-f1ec-49b9-b645-3194c9f1e795)
