### ISSUE TITLE
Create PopularRecipes component

### ISSUE THREAD

**Issue by AndriyBabiy** [asaulyak/foodies-fe#20]
"Компонент містить:
- заголовок секції
- список популярних рецептів, елементи якого є універсальним компонентом RecipeCard, описаний вище"

**Comment by didukhroma** [comment]
Original DB response


![Image](https://github.com/user-attachments/assets/ba3dfff8-86ca-410d-ad0f-105dcb67ad95)

In local DB all ok


![Image](https://github.com/user-attachments/assets/7126c84a-fcae-4f47-b6ae-d07f7bce2a5b)
